<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>OmegaWarhead</AssemblyName>
    <RootNamespace>OmegaWarhead</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\Release\</OutputPath>
    <!-- Strong Name Signing -->
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>OmegaWarhead.snk</AssemblyOriginatorKeyFile>
    <!-- DNT_OF watermark -->
    <Copyright>DNT_OF</Copyright>
    <Company>DNT_OF</Company>
  </PropertyGroup>

  <!-- EXILED NuGet -->
  <ItemGroup>
    <PackageReference Include="ExMod.Exiled" Version="*" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Exiled.CustomItems">
      <HintPath>lib\Exiled.CustomItems.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>lib\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>lib\UnityEngine.CoreModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HintServiceMeow" Version="*" />
  </ItemGroup>

</Project>
